from __future__ import annotations

from typing import Protocol

from app.models.domain import (
    ModerationConfig,
    ModerationLog,
    Review,
    ReviewFusionDecision,
    ReviewImageAnalysis,
    ReviewMedia,
    ReviewTextAnalysis,
    ReviewVideoAnalysis,
)
from app.models.enums import ReviewStatus


class ReviewRepository(Protocol):
    def save_review(self, review: Review) -> Review: ...

    def list_reviews(self) -> list[Review]: ...

    def get_review(self, review_id: str) -> Review | None: ...

    def delete_review(self, review_id: str) -> bool: ...

    def update_review_status(self, review_id: str, status: ReviewStatus, *, is_published: bool | None = None) -> Review: ...

    def save_media(self, media: ReviewMedia) -> ReviewMedia: ...

    def get_review_media(self, review_id: str) -> list[ReviewMedia]: ...

    def save_text_analysis(self, analysis: ReviewTextAnalysis) -> ReviewTextAnalysis: ...

    def get_text_analysis(self, review_id: str) -> ReviewTextAnalysis | None: ...

    def save_image_analysis(self, analysis: ReviewImageAnalysis) -> ReviewImageAnalysis: ...

    def get_image_analysis_for_review(self, review_id: str) -> list[ReviewImageAnalysis]: ...

    def save_video_analysis(self, analysis: ReviewVideoAnalysis) -> ReviewVideoAnalysis: ...

    def get_video_analysis_for_review(self, review_id: str) -> list[ReviewVideoAnalysis]: ...

    def save_fusion_decision(self, decision: ReviewFusionDecision) -> ReviewFusionDecision: ...

    def get_fusion_decision(self, review_id: str) -> ReviewFusionDecision | None: ...

    def save_log(self, log: ModerationLog) -> ModerationLog: ...

    def get_logs(self, review_id: str) -> list[ModerationLog]: ...

    def get_config(self) -> ModerationConfig: ...

    def update_config(self, config: ModerationConfig) -> ModerationConfig: ...
